import type { JobPosting } from "@prisma/client";
import { runAgent } from "@/lib/agents/run-agent";
import { fallbackCoverLetterSignals, type ApplicationEvidencePlan, type HiringManagerMaterialReview } from "@/lib/applications/material-quality";
import { prisma } from "@/lib/prisma";

export type HiringManagerReviewerInput = {
  jobPostingId: string;
  userId?: string;
  coverLetterBody: string;
  generatedBy?: string | null;
  evidencePlan?: ApplicationEvidencePlan | null;
  applicationQa?: Record<string, unknown> | null;
};

export async function runHiringManagerReviewerAgent(input: HiringManagerReviewerInput) {
  return runAgent<unknown, HiringManagerMaterialReview>({
    agentType: "HIRING_MANAGER_REVIEWER",
    input: {
      jobPostingId: input.jobPostingId,
      userId: input.userId,
      generatedBy: input.generatedBy,
      coverLetterLength: input.coverLetterBody.length,
      evidenceRefs: input.evidencePlan?.evidenceRefs ?? [],
      applicationQaStatus: typeof input.applicationQa?.status === "string" ? input.applicationQa.status : null,
    },
    userId: input.userId,
    execute: async () => {
      const job = await prisma.jobPosting.findUnique({ where: { id: input.jobPostingId } });
      if (!job) throw new Error("Job posting not found.");
      return reviewCoverLetterForHiringManager({
        job,
        coverLetterBody: input.coverLetterBody,
        generatedBy: input.generatedBy,
        evidencePlan: input.evidencePlan,
        applicationQa: input.applicationQa,
      });
    },
  });
}

export function reviewCoverLetterForHiringManager({
  job,
  coverLetterBody,
  generatedBy,
  evidencePlan,
  applicationQa,
}: {
  job: Pick<JobPosting, "company" | "title" | "description" | "requirements" | "niceToHaves">;
  coverLetterBody: string;
  generatedBy?: string | null;
  evidencePlan?: ApplicationEvidencePlan | null;
  applicationQa?: Record<string, unknown> | null;
}): HiringManagerMaterialReview {
  const concerns: string[] = [];
  const unsupportedClaims: string[] = [];
  const genericSignals = fallbackCoverLetterSignals(coverLetterBody);
  const missingSignals: string[] = [];
  const strengths: string[] = [];
  const jobText = `${job.title} ${job.company} ${job.description} ${job.requirements ?? ""} ${job.niceToHaves ?? ""}`;
  const requiredSignals = roleSignals(jobText);
  const body = coverLetterBody.toLowerCase();

  if (generatedBy === "deterministic_fallback") concerns.push("Generated by deterministic fallback instead of structured cover-letter writer.");
  if (!mentionsCompany(coverLetterBody, job.company)) concerns.push("Does not clearly anchor to the company.");
  if (!mentionsRole(coverLetterBody, job.title)) concerns.push("Does not clearly anchor to the target role.");
  if (coverLetterBody.split(/\s+/).filter(Boolean).length < 150) concerns.push("Too short to show specific role fit.");
  if (genericSignals.length) concerns.push("Contains fallback or generic application phrasing.");
  if (!evidencePlan) concerns.push("Missing application evidence plan.");
  else if (evidencePlan.status !== "READY") concerns.push("Evidence plan has insufficient job-specific proof.");
  else strengths.push(`Uses ${evidencePlan.proofPoints.length} curated proof point${evidencePlan.proofPoints.length === 1 ? "" : "s"}.`);

  for (const signal of requiredSignals) {
    if (!body.includes(signal)) missingSignals.push(signal);
  }
  if (missingSignals.length >= Math.max(3, Math.ceil(requiredSignals.length / 2))) {
    concerns.push("Misses too many important job signals.");
  }

  const qaUnsupported = stringArray(applicationQa?.unsupportedClaims);
  if (qaUnsupported.length) unsupportedClaims.push(...qaUnsupported);
  const qaStatus = typeof applicationQa?.status === "string" ? applicationQa.status : null;
  if (qaStatus && qaStatus !== "PASS") concerns.push("Application QA requires review.");

  const evidenceText = evidencePlan?.proofPoints.map((point) => `${point.title} ${point.summary}`).join(" ") ?? "";
  if (/\b(ar|vr|augmented reality|virtual reality|defense|military|combat)\b/i.test(evidenceText) && !/\b(ar|vr|augmented reality|virtual reality|defense|military|combat|mission)\b/i.test(jobText)) {
    concerns.push("Uses unrelated AR, VR, defense, or military proof points for a product engineering role.");
  }

  const score = Math.max(0, Math.min(100,
    100
      - concerns.length * 10
      - unsupportedClaims.length * 18
      - genericSignals.length * 12
      - missingSignals.length * 4,
  ));
  const hardBlocked = generatedBy === "deterministic_fallback"
    || genericSignals.length > 0
    || unsupportedClaims.length > 0
    || score < 70;
  const status: HiringManagerMaterialReview["status"] = hardBlocked ? "BLOCKED" : score >= 85 && concerns.length === 0 ? "PASS" : "NEEDS_REVIEW";
  const rewriteRecommended = status === "NEEDS_REVIEW" && generatedBy !== "deterministic_fallback";

  return {
    status,
    score,
    strengths,
    concerns,
    missingSignals,
    unsupportedClaims,
    genericSignals,
    rewriteRecommended,
    rewriteInstructions: rewriteRecommended
      ? rewriteInstructions(job, concerns, missingSignals, evidencePlan)
      : null,
    reasoningSummary: `Reviewed ${job.company}'s ${job.title} cover letter for hiring-manager relevance, specificity, and evidence fit.`,
    confidence: evidencePlan?.status === "READY" ? 0.84 : 0.62,
  };
}

function roleSignals(text: string) {
  const normalized = text.toLowerCase();
  const signals = [
    "react", "typescript", "full stack", "full-stack", "node", "graphql", "postgresql", "product", "ux",
    "performance", "editor", "component", "ai", "agent", "async", "startup", "customer-facing",
  ];
  return Array.from(new Set(signals.filter((signal) => normalized.includes(signal)))).slice(0, 8);
}

function mentionsCompany(body: string, company: string) {
  const token = company.toLowerCase().split(/\s+/)[0];
  return token.length > 1 && body.toLowerCase().includes(token);
}

function mentionsRole(body: string, title: string) {
  const bodyText = body.toLowerCase();
  return title.toLowerCase().split(/\s+|\/|-/).some((part) => part.length > 4 && bodyText.includes(part));
}

function rewriteInstructions(
  job: Pick<JobPosting, "company" | "title">,
  concerns: string[],
  missingSignals: string[],
  evidencePlan?: ApplicationEvidencePlan | null,
) {
  return [
    `Rewrite for ${job.company}'s ${job.title} role with direct hiring-manager relevance.`,
    concerns.length ? `Fix: ${concerns.join("; ")}.` : null,
    missingSignals.length ? `Make supported signals visible: ${missingSignals.slice(0, 6).join(", ")}.` : null,
    evidencePlan?.proofPoints.length
      ? `Use these proof points: ${evidencePlan.proofPoints.map((point) => `${point.title}: ${point.summary}`).slice(0, 3).join(" | ")}.`
      : null,
    "Avoid generic enthusiasm, fallback scaffolding, and forced Job Search OS/Agentic assistant paragraphs unless the job-specific evidence makes it directly relevant.",
  ].filter(Boolean).join(" ");
}

function stringArray(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string" && item.trim().length > 0) : [];
}
